services:
  dns:
    build: ./dns
    ports:
      - "5453:53/udp"
      - "5453:53/tcp"
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./dns/hosts:/etc/dnsmasq-hosts:ro
    networks:
      fluent-bit-lab:
        ipv6_address: 2001:db8::2

  server:
    image: nginx:alpine
    ports:
      - "8080:80"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
    command: >
      sh -c "
        for i in $$(seq 10 29); do
          ip addr add 2001:db8::$$i/64 dev eth0;
        done;
        exec nginx -g 'daemon off;'
      "
    networks:
      fluent-bit-lab:
        ipv6_address: 2001:db8::9
    depends_on:
      - dns

  # Docker Desktop can have issues correctly propagating the 'dns' option
  # to containers, causing them to default to an internal resolver.
  # To work around this, we mount a custom resolv.conf to force
  # the fluent-bit containers to use our DNS service directly.
  fluent-bit-default:
    image: fluent/fluent-bit:4.0.4
    volumes:
      - ./fluent-bit:/fluent-bit/etc:ro
      - ./fluent-bit/resolv.conf:/etc/resolv.conf:ro
    command: -c /fluent-bit/etc/fluent-bit-default.conf
    networks:
      fluent-bit-lab:
        ipv6_address: 2001:db8::100
    depends_on:
      - dns
      - server
    dns:
      - 2001:db8::2

    # The fluent/fluent-bit distroless image does not always respect the 'dns'
    # option and defaults to Docker's internal resolver.
    # We mount a custom resolv.conf to force it to use our DNS container.
  fluent-bit-dns-tcp:
    image: fluent/fluent-bit:4.0.4
    # The fluent/fluent-bit distroless image does not always respect the 'dns'
    # option and defaults to Docker's internal resolver.
    # We mount a custom resolv.conf to force it to use our DNS container.
    volumes:
      - ./fluent-bit:/fluent-bit/etc:ro
      - ./fluent-bit/resolv.conf:/etc/resolv.conf:ro
    command: -c /fluent-bit/etc/fluent-bit-dns-tcp.conf
    networks:
      fluent-bit-lab:
        ipv6_address: 2001:db8::101
    depends_on:
      - dns
      - server
    dns:
      - 2001:db8::2

networks:
  fluent-bit-lab:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: 2001:db8::/64
