services:
  dns:
    build: ./dns
    ports:
      - "5453:53/udp"
      - "5453:53/tcp"
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./dns/hosts:/etc/dnsmasq-hosts:ro
    networks:
      fluent-bit-lab:
        ipv6_address: 2001:db8::2

  server:
    image: nginx:alpine
    ports:
      - "8080:80"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
    command: >
      sh -c "
        for i in $$(seq 10 29); do
          ip addr add 2001:db8::$$i/64 dev eth0;
        done;
        exec nginx -g 'daemon off;'
      "
    networks:
      fluent-bit-lab:
        ipv6_address: 2001:db8::9
    depends_on:
      - dns

  fluent-bit-default:
    extends:
      file: docker-compose.base.yml
      service: fluent-bit-default
    image: fluent/fluent-bit:4.0.4

  fluent-bit-dns-tcp:
    extends:
      file: docker-compose.base.yml
      service: fluent-bit-dns-tcp
    image: fluent/fluent-bit:4.0.4

networks:
  fluent-bit-lab:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: 2001:db8::/64
